const stores = [
    { linkimg: 'https://m.media-amazon.com/images/I/61BJypg9XsL._AC_SX679_.jpg', linkproduct: 'https://amzn.to/3TcViQJ' },
    { linkimg: 'https://m.media-amazon.com/images/I/51WyZ0rPveL._AC_SX679_.jpg', linkproduct: 'https://amzn.to/3FCtd24' },
    { linkimg: 'https://m.media-amazon.com/images/I/71icKMNl4OS._AC_SX679_.jpg', linkproduct: 'https://amzn.to/3FVPLLc' },
    { linkimg: 'https://m.media-amazon.com/images/I/711PoknqL6S._AC_SX679_.jpg', linkproduct: 'https://amzn.to/441JRjs' },
    { linkimg: 'https://m.media-amazon.com/images/I/71PA07Cw6sL.__AC_SX300_SY300_QL70_FMwebp_.jpg', linkproduct: 'https://amzn.to/3ZyuKge' },
    { linkimg: 'https://m.media-amazon.com/images/I/31RWzzZ8nXL._SX300_SY300_QL70_FMwebp_.jpg', linkproduct: 'https://amzn.to/4kZq1fQ' },
    { linkimg: 'https://images-na.ssl-images-amazon.com/images/I/6134gR-j5kL._AC_UL600_SR600,400_.jpg', linkproduct: 'https://amzn.to/3ZuQREh' },
    { linkimg: 'https://m.media-amazon.com/images/I/71taFV+bVZL._AC_SY300_SX300_.jpg', linkproduct: 'https://amzn.to/4l5zx0X' },
    { linkimg: 'https://m.media-amazon.com/images/I/51qiE+X+42L._AC_SX679_.jpg', linkproduct: 'https://amzn.to/3Zz5M09' },
    { linkimg: 'https://m.media-amazon.com/images/I/61NtcjW9VPL._AC_SX679_.jpg', linkproduct: 'https://amzn.to/4mYfwv7' },
    { linkimg: 'https://m.media-amazon.com/images/I/71QH9AA42ML.__AC_SX300_SY300_QL70_FMwebp_.jpg', linkproduct: 'https://amzn.to/45pxZKD' },
    { linkimg: 'https://m.media-amazon.com/images/I/51e52o8WhYL.__AC_SX300_SY300_QL70_FMwebp_.jpg', linkproduct: 'https://amzn.to/3HGmm8o' },
    { linkimg: 'https://m.media-amazon.com/images/I/31QUUyeB5lL._SX300_SY300_QL70_FMwebp_.jpg', linkproduct: 'https://amzn.to/3SWRvH4' },
    { linkimg: 'https://m.media-amazon.com/images/I/61IRxZQKIyL._SX466_.jpg', linkproduct: 'https://amzn.to/45mYYqc' },
    { linkimg: 'https://m.media-amazon.com/images/I/41LLINlLziL._SX300_SY300_QL70_FMwebp_.jpg', linkproduct: 'https://amzn.to/4e8XiCX' },
    { linkimg: 'https://m.media-amazon.com/images/I/41Mz-8+5SBL._SY300_SX300_.jpg', linkproduct: 'https://amzn.to/4jQdXfN' },
    { linkimg: 'https://m.media-amazon.com/images/I/319VhbtqxGL._SX300_SY300_QL70_FMwebp_.jpg', linkproduct: 'https://amzn.to/3FYxAV8' },
    { linkimg: 'https://m.media-amazon.com/images/I/61K6cQhw4EL._SX679_.jpg', linkproduct: 'https://amzn.to/3Tsnzmc' },
    { linkimg: 'https://m.media-amazon.com/images/I/81URBn+E5aL._AC_SX679_.jpg', linkproduct: 'https://amzn.to/4nnb09N' },
    { linkimg: 'https://m.media-amazon.com/images/I/81JjF1+K6gL._AC_SY879_.jpg', linkproduct: 'https://amzn.to/3ZvptpO' },
    { linkimg: 'https://m.media-amazon.com/images/I/81PHnCv3OCL._AC_SX679_.jpg', linkproduct: 'https://amzn.to/4jVnBxI' },
    { linkimg: 'https://m.media-amazon.com/images/I/81wvyvlrbQS.__AC_SX300_SY300_QL70_FMwebp_.jpg', linkproduct: 'https://amzn.to/3G2R8aX' },
    { linkimg: 'https://m.media-amazon.com/images/I/61Y+DP+L3fL._AC_SX679_.jpg', linkproduct: 'https://amzn.to/4eaVYj4' },
    { linkimg: 'https://m.media-amazon.com/images/I/81AHrm8rhWL._AC_SX679_.jpg', linkproduct: 'https://amzn.to/4kJfplo' }
  ];